export const ALL_ITEMS = {
    'espada_basica': { name: 'Lâmina Fragmentada', rarity: 'basic', desc: 'Inicia a partida com +15% de Dano Físico.' },
    'escudo_ferro': { name: 'Escudo Primitivo', rarity: 'basic', desc: 'Inicia a partida com +15% de Defesa.' },
    'bota_velocidade': { name: 'Propulsor de Íons', rarity: 'basic', desc: 'Inicia a partida com +10% de Velocidade de Movimento.' },
    'pocao_vida': { name: 'Injetor de Nanobots', rarity: 'basic', desc: 'Inicia a partida com +20% de HP Máximo.' },
    'armadura_aco': { name: 'Chassi Reforçado', rarity: 'basic', desc: 'Inicia a partida com +10% de Defesa e +10% de HP Máximo.' },
    'amuleto_magico': { name: 'Núcleo de Ressonância', rarity: 'epic', desc: 'Reduz o tempo de recarga de todas as habilidades em 15%.' },

    // --- 🟢 ITENS BÁSICOS ---
    'prisma_faiscas': { name: 'Prisma de Faiscas', rarity: 'basic', desc: '5% de chance ao atacar de aplicar Queimadura (Ignite).' },
    'cubo_toxico': { name: 'Cubo Tóxico', rarity: 'basic', desc: '5% de chance ao atacar de aplicar 1 stack de Veneno (Poison).' },
    'lamina_triangular': { name: 'Lâmina Triangular', rarity: 'basic', desc: 'Ataques ganham 5% de chance de aplicar Sangramento (Bleed).' },
    'cilindro_corrosivo': { name: 'Cilindro Corrosivo', rarity: 'basic', desc: '3% de chance de aplicar Corrosão (Acid).' },
    'orbe_enfermo': { name: 'Orbe Enfermo', rarity: 'basic', desc: '2% de chance de aplicar Praga (Plague) no inimigo.' },
    'icosaedro_gelido': { name: 'Icosaedro Gélido', rarity: 'basic', desc: '1% de chance de causar Congelamento (Freeze) por 1s.' },
    'bloco_pesado': { name: 'Bloco Pesado', rarity: 'basic', desc: '2% de chance de aplicar Atordoamento (Stun).' },
    'raizes_poligonais': { name: 'Raízes Poligonais', rarity: 'basic', desc: '5% de chance de causar Enraizamento (Root).' },
    'cone_lentidao': { name: 'Cone da Lentidão', rarity: 'basic', desc: '10% de chance de aplicar Lentidão (Slow) de 20%.' },
    'luz_prismatica': { name: 'Luz Prismática', rarity: 'basic', desc: '2% de chance de causar Cegueira (Blind).' },
    'esfera_mudo': { name: 'Esfera do Mudo', rarity: 'basic', desc: '5% de chance de aplicar Silenciamento (Silence).' },
    'espelho_distorcido': { name: 'Espelho Distorcido', rarity: 'basic', desc: '3% de chance de causar Confusão (Confusion).' },
    'tetraedro_panico': { name: 'Tetraedro do Pânico', rarity: 'basic', desc: '2% de chance de causar Medo (Fear).' },
    'placa_provocador': { name: 'Placa do Provocador', rarity: 'basic', desc: 'Reduz o dano recebido de inimigos sob efeito de Provocação (Taunt) em 5%.' },
    'lente_fenda': { name: 'Lente da Fenda', rarity: 'basic', desc: '5% de chance de aplicar Vulnerabilidade (Vulnerable).' },
    'tijolo_exaustivo': { name: 'Tijolo Exaustivo', rarity: 'basic', desc: '5% de chance de aplicar Fraqueza (Weakness).' },
    'circulo_cansaco': { name: 'Círculo do Cansaço', rarity: 'basic', desc: '5% de chance de aplicar Exaustão (Exhaust).' },
    'seta_marcadora': { name: 'Seta Marcadora', rarity: 'basic', desc: '5% de chance de aplicar Marca do Caçador (Marked).' },
    'cunha_serrilhada': { name: 'Cunha Serrilhada', rarity: 'basic', desc: '5% de chance de aplicar Anti-Cura (Mortal Wounds).' },
    'cristal_vitalidade': { name: 'Cristal de Vitalidade', rarity: 'basic', desc: 'Inicia a partida com buff constante de Regeneração (Regen).' },
    'vento_cubico': { name: 'Vento Cúbico', rarity: 'basic', desc: 'Inicia a partida com Aceleração (Haste) (+5% Move/Atk Speed).' },
    'estilhaco_furia': { name: 'Estilhaço de Fúria', rarity: 'basic', desc: 'Se HP cair abaixo de 20%, ativa Fúria (Enrage) por 3s (Cooldown: 60s).' },
    'mini_escudo_planar': { name: 'Mini-Escudo Planar', rarity: 'basic', desc: 'Ao receber dano letal, ativa Escudo Divino (Aegis) por 1s (1 vez por partida).' },
    'cacto_geometrico': { name: 'Cacto Geométrico', rarity: 'basic', desc: 'Garante 5% de chance de aplicar o buff de Espinhos (Thorns) por 5s ao ser atacado.' },
    'presa_poligono': { name: 'Presa de Polígono', rarity: 'basic', desc: 'Garante +2% global de Vampirismo (Lifesteal).' },
    'peso_balanceador': { name: 'Peso Balanceador', rarity: 'basic', desc: '+10% de HP Máximo, aplica -5% permanente de Lentidão (Slow) em si mesmo.' },
    'motor_hasteado': { name: 'Motor Hasteado', rarity: 'basic', desc: 'Ganha +10% de MoveSpeed, mas aplica -5% de dano base.' },
    'frasco_sangue': { name: 'Frasco Quadrado de Sangue', rarity: 'basic', desc: 'Aumenta o dano do status Sangramento (Bleed) causado em 15%.' },
    'frasco_veneno': { name: 'Frasco Quadrado de Veneno', rarity: 'basic', desc: 'Aumenta o limite máximo de Stacks do seu Veneno (Poison) em +2.' },
    'relogio_triangular': { name: 'Relógio Triangular', rarity: 'basic', desc: 'Aumenta a duração de todos os status de CC (Freeze, Stun, Root) causados em +0.5s.' },

    // --- 🟣 ITENS ÉPICOS ---
    'dodecaedro_carnificina': { name: 'Dodecaedro da Carnificina', rarity: 'epic', desc: 'Se o inimigo estiver sob efeito de Sangramento, seus acertos críticos têm 100% de chance de aplicar Fúria (Enrage) em você por 2s.' },
    'bastiao_gelo': { name: 'Bastião de Gelo', rarity: 'epic', desc: 'Quando sua vida cai abaixo de 30%, ativa Escudo Divino (Aegis) por 3s e aplica Congelamento (Freeze) em área (AoE 5m) por 2s. (Cooldown: 120s).' },
    'casco_toxico': { name: 'Casco Tóxico Farpado', rarity: 'epic', desc: 'Aplica permanentemente Espinhos (Thorns) (+15%). Inimigos que sofrem dano dos seus espinhos recebem 2 stacks de Veneno (Poison).' },
    'lamina_sanguessuga': { name: 'Lâmina Sanguessuga', rarity: 'epic', desc: 'Aumenta seu Vampirismo (Lifesteal) em +5%. Se você atacar um alvo com Vulnerabilidade, o lifesteal dobra.' },
    'epidemia_acida': { name: 'Epidemia Ácida', rarity: 'epic', desc: 'Sempre que a sua Praga (Plague) se espalhar após a morte de um inimigo, ela espalha também 2 stacks de Corrosão (Acid).' },
    'olho_aterrorizante': { name: 'O Olho Aterrorizante', rarity: 'epic', desc: 'Ao receber dano corpo-a-corpo superior a 15% do seu HP máximo de uma vez, ativa Medo (Fear) no atacante e aplica Marca do Caçador (Marked) nele.' },
    'megafone_conico': { name: 'Megafone Cônico', rarity: 'epic', desc: 'A cada 30 segundos, emite um pulso que aplica Provocação (Taunt) em todos num raio de 10 metros, mas garante a você Escudo Divino (Aegis) por 3 segundos.' },
    'grilhoes_cansaco': { name: 'Grilhões do Cansaço', rarity: 'epic', desc: 'Todo inimigo que sofrer Enraizamento (Root) por você sofrerá automaticamente Exaustão (Exhaust) pelo dobro do tempo.' },
    'pendulo_curativo': { name: 'Pêndulo Curativo', rarity: 'epic', desc: 'Se você não receber dano por 10 segundos, ganha um buff fortíssimo de Regeneração (Regen). O buff cessa ao tomar dano, mas aplica Anti-Cura (Mortal Wounds) no atacante.' },
    'prisma_duelista': { name: 'Prisma do Duelista', rarity: 'epic', desc: 'Seus ataques alternam: o 1º golpe aplica Fraqueza (Weakness), o 2º aplica Queimadura (Ignite) e o 3º aplica Confusão (Confusion).' },

    // --- 🟠 ITENS LENDÁRIOS ---
    'cubo_infinito': { name: 'Cubo do Infinito', rarity: 'legendary', desc: 'A cada 10 segundos, alterna automaticamente o jogador entre 3 estados de Buff massivo contínuo: Regen+Haste, Enrage puro, Aegis intermitente.' },
    'prisma_calamidade': { name: 'Prisma da Calamidade', rarity: 'legendary', desc: 'Remove a sua habilidade de causar dano físico direto, mas 100% de seus acertos aplicam um "Super DoT" (Poison, Acid, Ignite, Plague).' },
    'tetraedro_distorcao': { name: 'Tetraedro da Distorção Temporal', rarity: 'legendary', desc: 'Você fica em estado permanente de Aceleração (Haste) Extrema (+50% Velocidade). Inimigos que entrarem num raio de 8 metros ao seu redor sofrem Lentidão (Slow) de -70% constante e perdem a habilidade de conjurar magias (Silenciamento).' },
    'coroa_gelida': { name: 'Coroa Gélida do Lich', rarity: 'legendary', desc: 'Seus ataques normais passam a ser golpes de gelo físico em área (AoE 45°). Inimigos atingidos são imobilizados por Congelamento (Freeze) por 1s. Todo dano causado a inimigos congelados concede 10% de Vampirismo (Lifesteal) direto para a vida máxima.' },
    'coracao_raziel': { name: 'O Coração Cúbico de Raziel', rarity: 'legendary', desc: '"Engana a Morte". Ao receber o golpe fatal, cura 100% HP, aplica Cegueira (Blind) e Confusão (Confusion) em toda a tela por 5s, e ganha Escudo Divino (Aegis) por 4s (1x por partida).' }
};

export const ITEM_ICONS = {
    'espada_basica': '🗡️',
    'escudo_ferro': '🛡️',
    'bota_velocidade': '🥾',
    'pocao_vida': '🧪',
    'armadura_aco': '🛡️',
    'amuleto_magico': '📿',

    // --- 🟢 ITENS BÁSICOS ---
    'prisma_faiscas': '🔸',
    'cubo_toxico': '🟢',
    'lamina_triangular': '🔺',
    'cilindro_corrosivo': '🔋',
    'orbe_enfermo': '🟣',
    'icosaedro_gelido': '❄️',
    'bloco_pesado': '⬜',
    'raizes_poligonais': '🪵',
    'cone_lentidao': '🔹',
    'luz_prismatica': '◽',
    'esfera_mudo': '⚫',
    'espelho_distorcido': '🪞',
    'tetraedro_panico': '🟣',
    'placa_provocador': '🟨',
    'lente_fenda': '🔍',
    'tijolo_exaustivo': '🧱',
    'circulo_cansaco': '⚪',
    'seta_marcadora': '🎯',
    'cunha_serrilhada': '⚙️',
    'cristal_vitalidade': '💎',
    'vento_cubico': '💨',
    'estilhaco_furia': '💥',
    'mini_escudo_planar': '🛡️',
    'cacto_geometrico': '🌵',
    'presa_poligono': '🦷',
    'peso_balanceador': '⚖️',
    'motor_hasteado': '⚙️',
    'frasco_sangue': '🧪',
    'frasco_veneno': '🧪',
    'relogio_triangular': '⏳',

    // --- 🟣 ITENS ÉPICOS ---
    'dodecaedro_carnificina': '🔴',
    'bastiao_gelo': '🛡️',
    'casco_toxico': '🐢',
    'lamina_sanguessuga': '🗡️',
    'epidemia_acida': '☣️',
    'olho_aterrorizante': '👁️',
    'megafone_conico': '📢',
    'grilhoes_cansaco': '⛓️',
    'pendulo_curativo': '🎚️',
    'prisma_duelista': '🔶',

    // --- 🟠 ITENS LENDÁRIOS ---
    'cubo_infinito': '♾️',
    'prisma_calamidade': '🔮',
    'tetraedro_distorcao': '🌀',
    'coroa_gelida': '👑',
    'coracao_raziel': '💖'
};

export const ITEM_IMAGES = {
    'espada_basica': 'item1.png',
    'escudo_ferro': 'item2.png',
    'bota_velocidade': 'item3.png',
    'pocao_vida': 'item4.png',
    'armadura_aco': 'item5.png',
    'amuleto_magico': 'item6.png',
    'prisma_faiscas': 'item7.png',
    'cubo_toxico': 'item8.png',
    'lamina_triangular': 'item9.png',
    'cilindro_corrosivo': 'item10.png',
    'orbe_enfermo': 'item11.png',
    'icosaedro_gelido': 'item12.png',
    'bloco_pesado': 'item13.png',
    'raizes_poligonais': 'item14.png',
    'cone_lentidao': 'item15.png',
    'luz_prismatica': 'item16.png',
    'esfera_mudo': 'item17.png',
    'espelho_distorcido': 'item18.png',
    'tetraedro_panico': 'item19.png',
    'placa_provocador': 'item20.png',
    'lente_fenda': 'item21.png',
    'tijolo_exaustivo': 'item22.png',
    'circulo_cansaco': 'item23.png',
    'seta_marcadora': 'item24.png',
    'cunha_serrilhada': 'item25.png',
    'cristal_vitalidade': 'item26.png',
    'vento_cubico': 'item27.png',
    'estilhaco_furia': 'item28.png',
    'mini_escudo_planar': 'item29.png',
    'cacto_geometrico': 'item30.png',
    'presa_poligono': 'item31.png',
    'peso_balanceador': 'item32.png',
    'motor_hasteado': 'item33.png',
    'frasco_sangue': 'item34.png',
    'frasco_veneno': 'item35.png',
    'relogio_triangular': 'item36.png',
    'dodecaedro_carnificina': 'item37.png',
    'bastiao_gelo': 'item38.png',
    'casco_toxico': 'item39.png',
    'lamina_sanguessuga': 'item40.png',
    'epidemia_acida': 'item41.png',
    'olho_aterrorizante': 'item42.png',
    'megafone_conico': 'item43.png',
    'grilhoes_cansaco': 'item44.png',
    'pendulo_curativo': 'item45.png',
    'prisma_duelista': 'item46.png',
    'cubo_infinito': 'item47.png',
    'prisma_calamidade': 'item48.png',
    'tetraedro_distorcao': 'item49.png',
    'coroa_gelida': 'item50.png',
    'coracao_raziel': 'item51.png'
};
